### ISSUE TITLE
Pseudo-Keyword Arguments

### ISSUE THREAD

**Issue by h0rs3r4dish** [practicingruby/rbp-book#4]
I'm not sure how those "pseudo-keyword arguments" work in the RBP code (ex "Ruby’s Secret Power: Flexible Argument Processing" pg 5):

```
# Pseudo-keyword arguments
def story(options)
  "#{options[:person]} went to town, riding on a #{options[:animal]}"
end
```

The example in the book is this:

```
story(animal: "Tiger", person: "Yankee Doodle")
# => "Yankee Doodle went to town, riding on a Tiger"
```

But if I enter that code into IRB:

```
irb(main):012:0> story(animal: "Tiger", person: "Yankee Doodle")
SyntaxError: compile error
(irb):12: syntax error, unexpected ':', expecting ')'
story(animal: "Tiger", person: "Yankee Doodle")
            ^
(irb):12: syntax error, unexpected ',', expecting $end
story(animal: "Tiger", person: "Yankee Doodle")
                     ^
    from (irb):12
    from :0
```

The example works if I use a hash (as I had expected):

```
irb(main):013:0> story(:animal => "Tiger", :person => "Yankee Doodle")
=> "Yankee Doodle went to town, riding on a Tiger"
```

So I'm wondering: how did the book's JSON/Python-esque code work? Is it running on Ruby 1.9 (1.8.7 here), or is there some hack I'm missing?

**Comment by practicingruby** [comment]
The book is indeed a Ruby 1.9.1 book.  This is mentioned in the "Audience" section of the preface, but I can see how just stumbling across that example could be confusing.

Perhaps when the open source version of the book heats up, someone could do a 1.8 branch of it, as really, there are only a few places (aside from the m17n chapter) in which I lean on Ruby 1.9 features.  That said, I will probably make the mainstream book take advantage of even more Ruby 1.9isms over time.

I know adoption has been slow, but Ruby 1.9 really is a better Ruby.  We should move forward when we can.
