### ISSUE TITLE
Fibonacci example doesn't work

### ISSUE THREAD

**Issue by hiaw** [practicingruby/rbp-book#9]
Hi,

Was reading your book and fascinated by the Fibonacci example with Memoization. Tried it out and it doesn't work. 

Attached is the code used and the error code

```
def fib(n) 
  @series[n] ||= fib(n-1) + fib(n-2)
end

p fib(50)
```

NoMethodError: undefined method `[]' for nil:NilClass

method fib          in test2.rb at line 2
at top level    in test2.rb at line 5

**Comment by practicingruby** [comment]
try this:

```
def fib(n) 
  @series ||= []
  @series[n] ||= fib(n-1) + fib(n-2)
end
```

**Comment by hiaw** [comment]
This works.

```
def fib(n)
  return n if (0..1).include? n
  @series ||= []
  @series[n] ||= fib(n-1) + fib(n-2)
end
```

**Comment by practicingruby** [comment]
Hah, right.  Sorry about that I didn't look closely enough.

That was a pretty bad error, thanks for pointing it out.
